# Generated by Django 4.2.4 on 2023-11-10 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instructions_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions_details', models.CharField(max_length=90)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='question_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=90)),
                ('option1', models.CharField(max_length=90)),
                ('option2', models.CharField(max_length=90)),
                ('option3', models.CharField(max_length=90)),
                ('option4', models.CharField(max_length=90)),
                ('result', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=90)),
                ('lastname', models.CharField(max_length=90)),
                ('gender', models.CharField(max_length=90)),
                ('place', models.CharField(max_length=90)),
                ('post', models.CharField(max_length=90)),
                ('pin', models.BigIntegerField()),
                ('qualification', models.CharField(max_length=90)),
                ('proof', models.FileField(upload_to='')),
                ('experience', models.CharField(max_length=90)),
                ('phonenumber', models.BigIntegerField()),
                ('email', models.CharField(max_length=90)),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='test_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('test', models.CharField(max_length=90)),
                ('details', models.CharField(max_length=90)),
                ('TEACHERS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.teacher_table')),
            ],
        ),
        migrations.CreateModel(
            name='studymaterials_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=90)),
                ('notes', models.FileField(upload_to='')),
                ('TEACHER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.teacher_table')),
            ],
        ),
        migrations.CreateModel(
            name='student_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=90)),
                ('lastname', models.CharField(max_length=90)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=90)),
                ('place', models.CharField(max_length=90)),
                ('post', models.CharField(max_length=90)),
                ('pin', models.BigIntegerField()),
                ('email', models.CharField(max_length=90)),
                ('photo', models.FileField(upload_to='')),
                ('phonenumber', models.BigIntegerField()),
                ('standard', models.CharField(max_length=90)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='salary_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('salary', models.CharField(max_length=90)),
                ('TEACHER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.teacher_table')),
            ],
        ),
        migrations.CreateModel(
            name='result_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('result', models.CharField(max_length=90)),
                ('QUESTION_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.question_table')),
                ('TEACHER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.student_table')),
            ],
        ),
        migrations.CreateModel(
            name='request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=90)),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.student_table')),
                ('TEACHER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.teacher_table')),
            ],
        ),
        migrations.AddField(
            model_name='question_table',
            name='TEST_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.test_table'),
        ),
        migrations.CreateModel(
            name='paymeny_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('SALARY_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.salary_table')),
            ],
        ),
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fee', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('REQUEST_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.request_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=90)),
                ('rating', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.student_table')),
                ('TEACHER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.teacher_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complaint', models.CharField(max_length=90)),
                ('reply', models.CharField(max_length=90)),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.student_table')),
            ],
        ),
        migrations.CreateModel(
            name='chat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chatbox', models.CharField(max_length=90)),
                ('FROM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to='sapp.login_table')),
                ('TO_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='sapp.login_table')),
            ],
        ),
    ]
